language: go
go:
 - 1.1
 - 1.2
 - release
 - tip
before_install:
 - sudo apt-get update -qq
install:
 - go get github.com/svenkreiss/dockbroker/dockbroker
 - go get github.com/svenkreiss/dockbroker/docksubmit
 - go get -v ./...
